### ISSUE TITLE
Which version of Firefox works with selenium 3.3.1 and gecko 0.15

### ISSUE THREAD

**Issue by fatenBAB** [mozilla/geckodriver#576]

**Comment by andreastt** [comment]
You should use [Firefox Nightly](https://nightly.mozilla.org/).

**Comment by fatenBAB** [comment]
It did not solve the problem, The browser is open but there is no action on it, no access to the web site entered in the code.

result: 
cucumber.runtime.CucumberException: org.openqa.selenium.SessionNotCreatedException: a.addEventListener is not a function
Command duration or timeout: 0 milliseconds

	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.openqa.selenium.SessionNotCreatedException: a.addEventListener is not a function
Command duration or timeout: 0 milliseconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:367)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:113)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.execute(NewProfileExtensionConnection.java:159)
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.execute(FirefoxDriver.java:433)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:121)
	at Steps.Hook.InitializeTest(Hook.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
	at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:202)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
	at cucumber.runtime.model.CucumberScenarioOutline.run(CucumberScenarioOutline.java:46)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:63)
	... 30 more
Caused by: org.openqa.selenium.SessionNotCreatedException: a.addEventListener is not a function
Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
System info: host: 'FATEN-PC', ip: '192.168.56.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: driver.version: unknown
	at <anonymous class>.wdSession.prototype.setWindow(file:///C:/Users/faten/AppData/Local/Temp/anonymous4854140354893193596webdriver-profile/extensions/fxdriver@googlecode.com/components/session.js:5155)
	at <anonymous class>.wdSession.prototype.setChromeWindow(file:///C:/Users/faten/AppData/Local/Temp/anonymous4854140354893193596webdriver-profile/extensions/fxdriver@googlecode.com/components/session.js:5149)
	at <anonymous class>.nsCommandProcessor.prototype.newSession(file:///C:/Users/faten/AppData/Local/Temp/anonymous4854140354893193596webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12850)
	at <anonymous class>.nsCommandProcessor.prototype.execute(file:///C:/Users/faten/AppData/Local/Temp/anonymous4854140354893193596webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12739)
	at <anonymous class>.Dispatcher.executeAs/<(file:///C:/Users/faten/AppData/Local/Temp/anonymous4854140354893193596webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10551)
	at <anonymous class>.Resource.prototype.handle(file:///C:/Users/faten/AppData/Local/Temp/anonymous4854140354893193596webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10698)
	at <anonymous class>.Dispatcher.prototype.dispatch(file:///C:/Users/faten/AppData/Local/Temp/anonymous4854140354893193596webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10645)
	at <anonymous class>.handle(file:///C:/Users/faten/AppData/Local/Temp/anonymous4854140354893193596webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:12547)
	at <anonymous class>.createHandlerFunc/<(file:///C:/Users/faten/AppData/Local/Temp/anonymous4854140354893193596webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:2054)
	at <anonymous class>.handleResponse(file:///C:/Users/faten/AppData/Local/Temp/anonymous4854140354893193596webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:2387)
	at <anonymous class>.process(file:///C:/Users/faten/AppData/Local/Temp/anonymous4854140354893193596webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:1223)
	at <anonymous class>._handleResponse(file:///C:/Users/faten/AppData/Local/Temp/anonymous4854140354893193596webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:1677)
	at <anonymous class>._processBody(file:///C:/Users/faten/AppData/Local/Temp/anonymous4854140354893193596webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:1525)
	at <anonymous class>.onInputStreamReady(file:///C:/Users/faten/AppData/Local/Temp/anonymous4854140354893193596webdriver-profile/extensions/fxdriver@googlecode.com/components/httpd.js:1393)

**Comment by ssaurav-1987** [comment]
I think proxy has not been setted in your code. Create object of JsonObject class and add property of proxyType, httpProxy and whatever proxy you have

**Comment by whimboo** [comment]
@fatenBAB you are not using Marionette/geckodriver but the old fxdriver. Check the log entries for `fxdriver@googlecode.com`.
