### ISSUE TITLE
selenium not working with mozilla 54.0.1

### ISSUE THREAD

**Issue by pawarsam** [mozilla/geckodriver#810]
In order to help us efficiently investigate your issue, please provide the following information:

## Platform and application details
* Platform: Windows 8
* Firefox: 54.0.1
* Selenium: 3.4.0

During execute selenium script through eclipse following error is displayed 

Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V  

though geckodriver (0.17) and guava jar (21.0) are up-to date

**Comment by raffam** [comment]
I have the exact same version of Firefox and Selenium and Windows 10. I use the Python bindings of Selenium and I don't have any of that error. Selenium works fine for me. Maybe you should also post the script that causes this error

**Comment by pawarsam** [comment]
Thanks for your reply @raffam , this issue is solved. I removed guava jar 19.0 from jar files. then its work for me, but now when i execute script i am facing mozilla "accessibility feature partially disabled..."  issue.
![mozilla issue](https://user-images.githubusercontent.com/29957704/27995344-579303ac-64ea-11e7-8a49-71a337b96985.png)

**Comment by andreastt** [comment]
As far as I can understand from https://searchfox.org/mozilla-central/source/browser/components/nsBrowserGlue.js#2792, that prompt is shown when e10s (multiprocess Firefox) is enabled and you have accessibility features enabled in your system.

I can’t see any way for us to disable that easily from Marionette, so I would recommend turning off accessibility when running geckodriver.

**Comment by whimboo** [comment]
I don't think we should force enabling it with Marionette because it would cause code paths currently marked as fragile in Firefox. Tests won't be stable. So as @andreastt said please disable accessibility or e10s. Whatever is less important to you.

**Comment by pawarsam** [comment]
yes i agree with @whimboo

**Comment by franzliedke** [comment]
@whimboo Sorry to lift up this old thread, but how do I disable e10s using Selenium/Geckodriver?

**Comment by andreastt** [comment]
With recent Firefoxen it is no longer possible to disable e10s/multiprocessing. If you are having issues using geckodriver with e10s enabled, I would suggest to file a new issue.
