### ISSUE TITLE
selenium not working with mozilla 54.0.1 and geckodriver (0.18)

### ISSUE THREAD

**Issue by KumarGaddam** [mozilla/geckodriver#845]
In order to help us efficiently investigate your issue, please provide the following information:

## Platform and application details
* Platform:  Windows 10
* Firefox: 54.0.1
* Selenium: 3.4.0

## Steps to reproduce
During execute selenium script through eclipse following error is displayed

Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V
	at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:136)
	at org.openqa.selenium.firefox.GeckoDriverService.access$000(GeckoDriverService.java:41)
	at org.openqa.selenium.firefox.GeckoDriverService$Builder.usingFirefoxBinary(GeckoDriverService.java:108)
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:204)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:108)
	at demo.Test1.main(Test1.java:23)

-

**Comment by jgraham** [comment]
Sorry, I have no idea what's wrong here from the selenum log. It looks like maybe an issue with selenium? If you can provide a trace-level geckodriver log as detailed in the README, I'm happy to reopen the issue and investigate further.

**Comment by pawarsam** [comment]
Remove guava 19.0 library and keep only latest 21.0  from exrernal library.
